### ISSUE TITLE
tenantName from config not propagated to passports OIDCStrategy

### ISSUE THREAD

**Issue by tence** [AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS#2]
I had to put add **tenantName: config.creds.tenantName** to the setup of the OIDCstrategy in app.js to make it working.

`passport.use(new OIDCStrategy({
    callbackURL: config.creds.returnURL,
    realm: config.creds.realm,
    clientID: config.creds.clientID,
    clientSecret: config.creds.clientSecret,
    oidcIssuer: config.creds.issuer,
    identityMetadata: config.creds.identityMetadata,
    skipUserProfile: config.creds.skipUserProfile,
    responseType: config.creds.responseType,
    responseMode: config.creds.responseMode,
    tenantName: config.creds.tenantName
  }, .... `

Also it might be useful to add the Info to your README, that you may to customize the SignIn and SignUp policy names (in index.ejs) to your B2C policy names.

**Comment by brandwe** [comment]
This has been fixed.
