### ISSUE TITLE
Problems with issuer

### ISSUE THREAD

**Issue by llorenssegui** [AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS#4]
I'm having problems when i use passport-azure-ad package. Partticullary, the output of app.js says this: 

{"name":"AzureAD: OIDC Passport Strategy","hostname":"Llorenç-PC","pid":14872,"level":40,"msg":"We are not validating the issuer. This is fine if you are expecting multiple organizations to connect to your app. Otherwise you should validate the issuer.","time":"2016-05-24T10:06:43.738Z","v":0}

How can I validate the issuer?

Other quation:

How can get id_token for obtain the user claims?

**Comment by brandwe** [comment]
Hello @llorenssegui! You may validate the issuer by setting the value to true in config.js. 

the id_token is provided in the profile and also should be the "token" included in the response in the sample. Hope this helps!
