### ISSUE TITLE
Authentication failed: Policy is missing

### ISSUE THREAD

**Issue by romangusev** [AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS#7]
I got this error while trying to authenticate a user against B2C:
`authentication failed due to: In collectInfoFromReq: policy is missing`

I have created my policy in B2C but I have no idea how and where I should specify it.

**Comment by lovemaths** [comment]
@romangusev policy is specified here: https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS/blob/master/views/index.ejs

In this sample, /login route is protected by passport, and passport extracts the policy query parameter in the request.

**Comment by romangusev** [comment]
@lovemaths Thanks a lot. I expected this info somewhere in this docs: [https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-web-node](url)
Because I have not cloned this repo, but trying to follow the docs and manually implement B2C with passport.
Anyway thanks for quick response.
