### ISSUE TITLE
Fetching Metadata is Broken

### ISSUE THREAD

**Issue by danderson00** [AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS#9]
I'm sure my configuration is correct, but I'm getting the "Cannot get AAD Federation metadata from endpoint you specified" error. In a browser, the specified endpoint works, but with the additional querystring parameters, it returns a 404.

For example, the specified endpoint is:
```
https://login.microsoftonline.com/<my tenant GUID>/v2.0/.well-known/openid-configuration
```
which returns the metadata, but with the additional querystring parameters, e.g.:
```
https://login.microsoftonline.com/<my tenant GUID>/v2.0/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.8&p=b2c_1_signin
```
a 404 is returned.

PLEASE, PLEASE, PLEASE make sure your documentation and samples are up to date. It is hard enough to come to grips with AAD in general due to inconsistent terminology, a multitude of configuration options and pages in the portal.

**Comment by danderson00** [comment]
After creating a signin policy with the appropriate name, i.e. `signin`, sign in now works. I ended up in this state because I followed a different tutorial to set up B2C that didn't mention this requirement. This requirement is not made clear enough!

**Comment by gsacavdm** [comment]
Can you share which tutorial you are referring to that didn't clarify this requirement so that we can update it accordingly?

**Comment by danderson00** [comment]
I'm pretty sure it's [this one](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-web-node). I also used the C# one, but that doesn't reference the passport strategy, of course, and doesn't have the same requirement.

The best solution would seem to me to allow specifying the policy names explicitly in the passport strategy configuration, but this isn't the place to discuss. Happy to open an issue in the `passport-azure-ad` repo if you'd like.
